# Generated by Django 4.1.5 on 2024-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер этажа')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('triple', 'Трехместный')], max_length=10, verbose_name='Тип номера')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за ночь')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('work_days', models.CharField(max_length=100, verbose_name='Дни работы')),
                ('floors', models.ManyToManyField(related_name='employees', to='rooms.floor', verbose_name='Этажи')),
            ],
        ),
    ]
