# Generated by Django 4.1.5 on 2024-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_description_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название номера'),
        ),
    ]
