# Generated by Django 4.1.5 on 2024-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, unique=True, verbose_name='День недели')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_days',
        ),
        migrations.AddField(
            model_name='employee',
            name='work_days',
            field=models.ManyToManyField(to='rooms.weekday', verbose_name='Дни работы'),
        ),
    ]
