# Generated by Django 4.1.5 on 2024-05-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_guest_guest_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
        ),
    ]
