# Generated by Django 4.1.5 on 2024-05-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Полная стоимость'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Статус платежа'),
        ),
    ]
